[package]
name = "adb-studio"
version = "0.1.0"
edition = "2021"
build = "build.rs"
authors = ["Alexandre Dupuis-Belin"]
description = "A cross-platform workspace for organizing and annotating generated audio."

[dependencies]
dirs = "6"
rfd = "0.15"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slint = "1.9"
symphonia = { version = "0.5", features = ["all"] }

[build-dependencies]
slint-build = "1.9"
